server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  port: 8901
  servlet:
    context-path: /kappa-talk
spring:
  data:
    mongodb:
      authentication-database: ${MONGO_AUTH_DB:}
      database: ${MONGO_DB:}
      uri: ${MONGO_CONNECTION_URL:}
  banner:
    location: banner.txt
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${AUTH_SERVICE:}
          client-id: ${CLIENT_ID:}
          client-secret: ${CLIENT_SECRET:}
custom:
  hazelcast-hosts: localhost
  http-port: 8900
  https-port: 8901
  security-policy: NONE
  connector-scheme: http
  enable-external-broker: false
logging:
  config: classpath:log4j-spring.xml

